### ISSUE TITLE
Cannot parse 12am

### ISSUE THREAD

**Issue by DylanPiercey** [millermedeiros/parse-loose-time#4]
None of the following work, they become PM.

``` console
12a -> 12:00pm
12am -> 12:00pm
12:00am -> 12:00pm
12:11am -> 12:11pm
```

Great work on this module otherwise!

**Comment by millermedeiros** [comment]
@DylanPiercey sorry for the huge delay, but today I finally found 10min to fix this and published v1.0.1 to npm :D
